---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: pdsl-bulk-sms-${ARGOCD_ENV_istio_internal_gateway_name}
  namespace: ${ARGOCD_ENV_istio_internal_gateway_namespace}
spec:
  selector:
    istio: ${ARGOCD_ENV_istio_internal_gateway_name}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.pdslkenya.com" 
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: pdsl-bulk-sms
  namespace: dev
spec:
  hosts:
  - "bulk-sms-portal.pdslkenya.com"
  gateways:
  - ${ARGOCD_ENV_istio_internal_gateway_namespace}/pdsl-bulk-sms-${ARGOCD_ENV_istio_internal_gateway_name}
  http:
  - route:
    - destination:
        host: sms-bulk-sms-portal.dev.svc.cluster.local
        port:
          number: 80
