apiVersion: batch/v1
kind: Job
metadata:
  name: curl-test-zitadel-vs
spec:
  template:
    spec:
      containers:
        - name: curl-test
          image: curlimages/curl:latest
          command: ["sh"]
          args:
            [
              "-c",
              "exit_status=$(curl -v -o /dev/null -w '%{http_code}' http://zitadel.${ARGOCD_ENV_zitadel_dns_subdomain}:31080); if [ $exit_status -ne 200 ] && [ $exit_status -ne 302 ]; then exit 1; fi;",
            ]
      restartPolicy: OnFailure
  backoffLimit: 10
