apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${ARGOCD_ENV_utils_rook_ceph_app_name}
  namespace: ${ARGOCD_ENV_utils_app_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: ${ARGOCD_ENV_utils_rook_ceph_sync_wave}

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${ARGOCD_ENV_utils_rook_ceph_namespace}
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.1

      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
        releaseName: longhorn
        #valuesObject:
        #  csi:
        #    kubeletDirPath: ${ARGOCD_ENV_utils_rook_ceph_rook_csi_kubelet_dir_path}
        #    serviceMonitor:
        #      interval: 60s
        #  enableDiscoveryDaemon: true
        #  monitoring:
        #    enabled: true
        #  resources:
        #    limits:
        #      memory: 512Mi
        #    requests:
        #      cpu: 50m
        #      memory: 64Mi
    - repoURL: ${ARGOCD_ENV_argocd_repo_url}
      targetRevision: ${ARGOCD_ENV_gitlab_application_gitrepo_tag}
      path: gitops/applications/base/longhorn
      plugin:
        name: envsubst
        env:
          - name: rook_ceph_namespace
            value: "${ARGOCD_ENV_utils_rook_ceph_namespace}"

          - name: objects_replica_count
            value: "${ARGOCD_ENV_utils_rook_ceph_objects_replica_count}"

